//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int post_id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string images { get; set; }
        public Nullable<int> users_id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
